spring:
  application:
    name: BudgetWise
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

seeder:
  countries:
    exclude: Israel,Western Sahara

jwt:
  secret: ${JWT_SECRET}
