spring:
  application:
    name: BudgetWise
  datasource:
    url: jdbc:mariadb://localhost:3306/budgetwise?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret: ${JWT_SECRET}
